/*
 Highcharts JS v6.1.4-modified (2018-10-01)
 X-range series

 (c) 2010-2017 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(h){"object"===typeof module&&module.exports?module.exports=h:"function"===typeof define&&define.amd?define(function(){return h}):h(Highcharts)})(function(h){(function(c){var h=c.addEvent,w=c.defined,x=c.Color,u=c.seriesTypes.column,l=c.each,v=c.isNumber,r=c.isObject,q=c.merge,p=c.pick,y=c.seriesType,z=c.Axis,t=c.Point,A=c.Series;y("xrange","column",{colorByPoint:!0,dataLabels:{verticalAlign:"middle",inside:!0,formatter:function(){var a=this.point.partialFill;r(a)&&(a=a.amount);w(a)||(a=
0);return 100*a+"%"}},tooltip:{headerFormat:'\x3cspan style\x3d"font-size: 0.85em"\x3e{point.x} - {point.x2}\x3c/span\x3e\x3cbr/\x3e',pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.yCategory}\x3c/b\x3e\x3cbr/\x3e'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:c.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,getColumnMetrics:function(){function a(){l(d.series,
function(a){var b=a.xAxis;a.xAxis=a.yAxis;a.yAxis=b})}var b,d=this.chart;a();b=u.prototype.getColumnMetrics.call(this);a();return b},cropData:function(a,b,d,f){b=A.prototype.cropData.call(this,this.x2Data,b,d,f);b.xData=a.slice(b.start,b.end);return b},translatePoint:function(a){var b=this.xAxis,d=this.columnMetrics,f=this.options,e=f.minPointLength||0,c=a.plotX,k=p(a.x2,a.x+(a.len||0)),g=b.translate(k,0,0,0,1),k=Math.abs(g-c),m=this.chart.inverted,n=p(f.borderWidth,1)%2/2;e&&(e-=k,0>e&&(e=0),c-=
e/2,g+=e/2);c=Math.max(c,-10);g=Math.min(Math.max(g,-10),b.len+10);f.pointPlacement&&v(a.plotY)&&this.yAxis.categories&&(a.plotY=this.yAxis.translate(a.y,0,1,0,1,f.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(c,g))+n,y:Math.floor(a.plotY+d.offset)+n,width:Math.round(Math.abs(g-c)),height:Math.round(d.width),r:this.options.borderRadius};f=a.shapeArgs.x;e=f+a.shapeArgs.width;0>f||e>b.len?(f=Math.min(b.len,Math.max(0,f)),e=Math.max(0,Math.min(e,b.len)),b=e-f,a.dlBox=q(a.shapeArgs,{x:f,width:e-
f,centerX:b?b/2:null})):a.dlBox=null;a.tooltipPos[0]+=m?0:k/2;a.tooltipPos[1]-=m?k/2:d.width/2;if(b=a.partialFill)r(b)&&(b=b.amount),v(b)||(b=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,height:d.height,r:this.options.borderRadius},a.clipRectArgs={x:d.x,y:d.y,width:Math.max(Math.round(k*b+(a.plotX-c)),0),height:d.height}},translate:function(){u.prototype.translate.apply(this,arguments);l(this.points,function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var d=this.options,
c=this.chart.renderer,e=a.graphic,h=a.shapeType,k=a.shapeArgs,g=a.partShapeArgs,m=a.clipRectArgs,n=a.partialFill,l=a.selected&&"select",p=d.stacking&&!d.borderRadius;if(a.isNull)e&&(a.graphic=e.destroy());else{if(e)a.graphicOriginal[b](q(k));else a.graphic=e=c.g("point").addClass(a.getClassName()).add(a.group||this.group),a.graphicOriginal=c[h](k).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(e);g&&(a.graphicOverlay?(a.graphicOverlay[b](q(g)),a.clipRect.animate(q(m))):(a.clipRect=
c.clipRect(m.x,m.y,m.width,m.height),a.graphicOverlay=c[h](g).addClass("highcharts-partfill-overlay").add(e).clip(a.clipRect)));a.graphicOriginal.attr(this.pointAttribs(a,l)).shadow(d.shadow,null,p);g&&(r(n)||(n={}),r(d.partialFill)&&(n=q(n,d.partialFill)),b=n.fill||x(a.color||this.color).brighten(-.3).get(),a.graphicOverlay.attr(this.pointAttribs(a,l)).attr({fill:b}).shadow(d.shadow,null,p))}},drawPoints:function(){var a=this,b=a.getAnimationVerb();l(a.points,function(c){a.drawPoint(c,b)})},getAnimationVerb:function(){return this.chart.pointCount<
(this.options.animationLimit||250)?"animate":"attr"}},{init:function(){t.prototype.init.apply(this,arguments);var a;a=this.series;var b=a.chart.options.chart.colorCount;this.y||(this.y=0);a.options.colorByPoint&&(a=a.options.colors||a.chart.options.colors,b=a.length,!this.options.color&&a[this.y%b]&&(this.color=a[this.y%b]));this.colorIndex=p(this.options.colorIndex,this.y%b);return this},setState:function(){t.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},
getLabelConfig:function(){var a=t.prototype.getLabelConfig.call(this),b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});h(z,"afterGetSeriesExtremes",function(){var a=this.series,b,c;this.isXAxis&&(b=p(this.dataMax,-Number.MAX_VALUE),l(a,function(a){a.x2Data&&l(a.x2Data,function(a){a>b&&(b=a,c=!0)})}),c&&(this.dataMax=b))})})(h)});
//# sourceMappingURL=xrange.js.map
