/*
 Highcharts JS v6.1.4-modified (2018-10-01)
 X-range series

 (c) 2010-2017 Torstein Honsi, Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?module.exports=f:"function"===typeof define&&define.amd?define(function(){return f}):f(Highcharts)})(function(f){(function(d){var f=d.addEvent,u=d.defined,q=d.seriesTypes.column,l=d.each,r=d.isNumber,t=d.isObject,m=d.merge,n=d.pick,v=d.seriesType,w=d.Axis,p=d.Point,x=d.Series;v("xrange","column",{colorByPoint:!0,dataLabels:{verticalAlign:"middle",inside:!0,formatter:function(){var a=this.point.partialFill;t(a)&&(a=a.amount);u(a)||(a=0);return 100*
a+"%"}},tooltip:{headerFormat:'\x3cspan style\x3d"font-size: 0.85em"\x3e{point.x} - {point.x2}\x3c/span\x3e\x3cbr/\x3e',pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.yCategory}\x3c/b\x3e\x3cbr/\x3e'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:d.seriesTypes.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,getColumnMetrics:function(){function a(){l(c.series,function(a){var b=
a.xAxis;a.xAxis=a.yAxis;a.yAxis=b})}var b,c=this.chart;a();b=q.prototype.getColumnMetrics.call(this);a();return b},cropData:function(a,b,c,e){b=x.prototype.cropData.call(this,this.x2Data,b,c,e);b.xData=a.slice(b.start,b.end);return b},translatePoint:function(a){var b=this.xAxis,c=this.columnMetrics,e=this.options,g=e.minPointLength||0,d=a.plotX,k=n(a.x2,a.x+(a.len||0)),h=b.translate(k,0,0,0,1),k=Math.abs(h-d),f=this.chart.inverted,l=n(e.borderWidth,1)%2/2;g&&(g-=k,0>g&&(g=0),d-=g/2,h+=g/2);d=Math.max(d,
-10);h=Math.min(Math.max(h,-10),b.len+10);e.pointPlacement&&r(a.plotY)&&this.yAxis.categories&&(a.plotY=this.yAxis.translate(a.y,0,1,0,1,e.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(d,h))+l,y:Math.floor(a.plotY+c.offset)+l,width:Math.round(Math.abs(h-d)),height:Math.round(c.width),r:this.options.borderRadius};e=a.shapeArgs.x;g=e+a.shapeArgs.width;0>e||g>b.len?(e=Math.min(b.len,Math.max(0,e)),g=Math.max(0,Math.min(g,b.len)),b=g-e,a.dlBox=m(a.shapeArgs,{x:e,width:g-e,centerX:b?b/2:null})):
a.dlBox=null;a.tooltipPos[0]+=f?0:k/2;a.tooltipPos[1]-=f?k/2:c.width/2;if(b=a.partialFill)t(b)&&(b=b.amount),r(b)||(b=0),c=a.shapeArgs,a.partShapeArgs={x:c.x,y:c.y,width:c.width,height:c.height,r:this.options.borderRadius},a.clipRectArgs={x:c.x,y:c.y,width:Math.max(Math.round(k*b+(a.plotX-d)),0),height:c.height}},translate:function(){q.prototype.translate.apply(this,arguments);l(this.points,function(a){this.translatePoint(a)},this)},drawPoint:function(a,b){var c=this.chart.renderer,e=a.graphic,d=
a.shapeType,f=a.shapeArgs,k=a.partShapeArgs,h=a.clipRectArgs;if(a.isNull)e&&(a.graphic=e.destroy());else{if(e)a.graphicOriginal[b](m(f));else a.graphic=e=c.g("point").addClass(a.getClassName()).add(a.group||this.group),a.graphicOriginal=c[d](f).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(e);k&&(a.graphicOverlay?(a.graphicOverlay[b](m(k)),a.clipRect.animate(m(h))):(a.clipRect=c.clipRect(h.x,h.y,h.width,h.height),a.graphicOverlay=c[d](k).addClass("highcharts-partfill-overlay").add(e).clip(a.clipRect)))}},
drawPoints:function(){var a=this,b=a.getAnimationVerb();l(a.points,function(c){a.drawPoint(c,b)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{init:function(){p.prototype.init.apply(this,arguments);var a=this.series.chart.options.chart.colorCount;this.y||(this.y=0);this.colorIndex=n(this.options.colorIndex,this.y%a);return this},setState:function(){p.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},
getLabelConfig:function(){var a=p.prototype.getLabelConfig.call(this),b=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=b&&b[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});f(w,"afterGetSeriesExtremes",function(){var a=this.series,b,c;this.isXAxis&&(b=n(this.dataMax,-Number.MAX_VALUE),l(a,function(a){a.x2Data&&l(a.x2Data,function(a){a>b&&(b=a,c=!0)})}),c&&(this.dataMax=b))})})(f)});
//# sourceMappingURL=xrange.js.map
